server:
  port: 8080

spring:
  application:
    name: banking-system

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres1
    password: postgres1

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
jwt:
  secret: "dGhpc0lzQVZlcnlMb25nRHVtbXlTZWNyZXRLZXlGb3JKV1RTaWduaW5nMTIzNA" # ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000